### ISSUE TITLE
urls for project in docs don't work

### ISSUE THREAD

**Issue by skyebend** [statnet/concurrency.sim#1]
Was just trying to refresh my memory about this project and found problems with the reference urls.  Are they just outdate? Was the first one that the one that was forwarded to the shiny server? maybe I broke it on migration?   Second one needs to be https.  or I should forward  http://statnet.org/trac/*  to the https site
# ' A web-based implementation of this model is available at
# ' \url{http://statnet.org/apps/Conc}. The background and details of this model
# ' are explained in a full tutorial on concurrency at
# ' \url{http://statnet.org/trac/wiki/ConcurrencyIndex}.

**Comment by smjenness** [comment]
This repository is a standalone R package to simulate a non-ergm model for concurrency. This used to be part of EpiModel, but it never really fit there, so therefore a standalone package, probably hosted only on Github for now. The shiny app for an old version of this was hosted at: http://spark.rstudio.com/statnet/Conc/ but as I make some updates to the code, I will be releasing this on our new statnet.shinyapps.io account. Nothing will be hosted on the statnet server, although the wiki page for the concurrency tutorial pointing to this will need to be updated: https://statnet.csde.washington.edu/trac/wiki/ConcurrencyExercise4C
