### ISSUE TITLE
Conditional mean degree slider

### ISSUE THREAD

**Issue by smjenness** [statnet/concurrency.sim#2]
@ebey If you have a minute, I would appreciate your thoughts on this.

In this concurrency simulation, there are four possibilities for concurrency, including "No Concurrency":
https://statnet.shinyapps.io/concurrency/

In this scenario, the mean degree is mathematically limited at 1 (one can't have more than one partner if one has no more than one partner!), and but the slider for mean degree allows for inputs up to 1.5, which is fine under the concurrency scenarios. I would like to try to make the values of the mean degree slider conditional on the value of the Concurrency scenario box.

I tried to do this on Server.R:

``` r
  output$mdControl <- renderUI({
    input$runMod
    concVal <- isolate(input$conc)
    mdConc <- ifelse(concVal == "No Concurrency", 1, 1.5)
    sliderInput(inputId = "md", label = "Mean Degree",
                min = 0.5, max = mdConc, value = 0.8, step = 0.05)
  })
```

where `input$conc` is the value of the concurrency drop down menu.

And this on the UI.R:

``` r
uiOutput("mdControl")
```

But it's not functioning correctly. The mean degree slider is hidden until the first model completes running, and does not change when the value of the concurrency drop down changes. 

Note this non-functioning version is in the condMD branch and can be run with:

``` r
runGitHub("statnet/concurrency.sim", ref = "condMD", subdir = "inst/shiny/app")
```

**Comment by ebey** [comment]
The `renderUI` function often doesn't work as expected for modifying input elements. I'm not sure why this is, but for most of these there are specific functions you can use to update their values (e.g. `updateSliderInput`).

See the UI Inputs section here: http://shiny.rstudio.com/reference/shiny/latest/

I have a working version that I'll push to the condMD branch.

**Comment by smjenness** [comment]
Fantastic, thank you shiny guru!
